package com.impact.be.service.app.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "customer-behaviour-db")
public class Customer {

    @DynamoDBHashKey
    //@DynamoDBAutoGeneratedKey
    @DynamoDBAttribute(attributeName = "Customer ID")
    private String id;

    @DynamoDBAttribute(attributeName = "Weather conditions")
    private String weatherConditions;
    
    @DynamoDBAttribute(attributeName = "Artist preference")
    private String artistPreference;
    
    @DynamoDBAttribute(attributeName = "Playlist preference")
    private String playlistPreference;
    
    @DynamoDBAttribute(attributeName = "Mood preference")
    private String moodPreference;
    
    @DynamoDBAttribute(attributeName = "Speeding incidents")
    private String  speedingIncidents;
    
    @DynamoDBAttribute(attributeName = "Frequency of hard braking")
    private String frequencyOfHardBraking;
    
    @DynamoDBAttribute(attributeName = "Distraction level")
    private String distractionLevel;
    
    @DynamoDBAttribute(attributeName = "Time of day")
    private String timeOfDay;
    
    @DynamoDBAttribute(attributeName = "Average time between vehicle maintenance")
    private String avgTimebtwVehicleMantnance;
    
    @DynamoDBAttribute(attributeName = "Speed")
    private String speed;
    
    @DynamoDBAttribute(attributeName = "Distance")
    private String distance;
    
    @DynamoDBAttribute(attributeName = "Time spent driving")
    private String timeSpentDriving;
    
    @DynamoDBAttribute(attributeName = "Fuel consumption")
    private String fuelConsumption;
    
    @DynamoDBAttribute(attributeName = "GPS location")
    private String gpsLocation;
    

	/*
	 * @DynamoDBAttribute private String lastName;
	 * 
	 * @DynamoDBAttribute private String email;
	 * 
	 * @DynamoDBAttribute private Address address;
	 */
}
